#!/usr/bin/env python3
"""Write ../MANIFEST.md from the static text below plus counts/tables computed from sources.csv, excerpts.jsonl,
searches.csv, defillama/index.csv and collect/fetch-log.jsonl. Re-run after any re-fetch."""
import csv, gzip, json, os, collections, datetime as dt

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.dirname(HERE)

QL = collections.OrderedDict([
    ('Q1-V4GAP', 'Uniswap V4 on Base. This is the biggest gap. Clanker and Zora launch new tokens as V4 pools with hooks, and I only had 20 V4 pools. The engine supports V4. It just doesn\'t list every V4 pool yet.'),
    ('Q2-OLDV2', 'Older V2 pairs. I took the newest 6,000 of about 3 million Uniswap V2 pairs. Almost all the older ones are abandoned tokens.'),
    ('Q3-SMALLPOOLS', 'Pools under 0.1 ETH of liquidity. Profit is capped at a slice of a pool\'s liquidity, so these pay a few dollars at most. They are also where most tokens that block or tax transfers sit.'),
    ('Q4-OTHERCHAINS', 'Other chains, live. The live search ran only on Base. Block-level scans covered Arbitrum and Ethereum. BSC, where PancakeSwap is biggest, Solana and the other L2s were not measured.'),
    ('Q5-V4LAUNCH', 'V4 launches are the one place a bigger number could appear. New launches open large, short-lived price gaps. It is also the most fought-over flow on Base.'),
    ('Q5-CONTEST', 'The RSR trade shows how contested gaps end: the winner kept 3% and paid the rest as priority fee. (Sources on how Base orders transactions and how priority fees are bid; the RSR trade itself is in research-material/05-base-onchain/rsr-episode and 00-prior-runs/competitor-ledgers.)'),
    ('Q6-BSCORDER', 'BSC has the same ordering problem. Its transaction ordering goes through private block builders, so a public bot still lands behind the incumbents.'),
    ('Q7-CHAINWIDE-METHOD', 'Chain-wide studies already count every pool. (Methodology passages: which pools/DEXes/transactions each study counts.)'),
    ('Q7-ARB-4700', 'On Arbitrum, atomic arbitrage totals about $4,700 a day for all bots combined.'),
    ('Q7-BASE-21M', 'On Base, 4,365 bots made 21.4 million arbitrages over nine months'),
    ('Q7-PROFIT-28', 'and only 28% of those bots were profitable after paying for failed transactions.'),
    ('Q8-V4MEASURE', 'So the search went far beyond selected pairs, but it did not cover everything. The one gap where I wouldn\'t predict the result is full Uniswap V4 coverage on Base. Measuring it means listing every V4 pool from the pool manager\'s creation events and rerunning the same 20-minute live test.'),
])


def rows(path):
    with open(path, newline='') as f:
        return list(csv.DictReader(f))


def main():
    src = rows(os.path.join(OUT, 'sources.csv'))
    exc = [json.loads(l) for l in open(os.path.join(OUT, 'excerpts.jsonl'))]
    srch = rows(os.path.join(OUT, 'searches.csv'))
    dl = rows(os.path.join(OUT, 'defillama', 'index.csv'))
    flog = [json.loads(l) for l in open(os.path.join(HERE, 'fetch-log.jsonl'))]
    ok = [s for s in src if s['status'] == 'ok']
    bad = [s for s in src if s['status'] != 'ok']
    ex_by_slug = collections.Counter(e['slug'] for e in exc)
    ex_by_q = collections.Counter(e['question_line'] for e in exc)
    times = sorted(r['t'] for r in flog) + sorted(r['fetched_at_utc'] for r in dl)
    tfirst, tlast = min(times), max(times)
    texts = sorted(os.listdir(os.path.join(OUT, 'texts')))
    raws = sorted(os.listdir(os.path.join(OUT, 'raw')))
    status_codes = collections.Counter(r['status'] for r in flog)

    L = []
    A = L.append
    A('# 08-sources: published sources behind the question lines (verbatim, with provenance)\n')
    A(f'Status: COMPLETE. Generated by `collect/make_manifest.py` at {dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}.')
    A('This folder holds fetched documents, verbatim excerpts, search records and raw DefiLlama JSON. It contains no analysis, findings or conclusions;')
    A('excerpts are exact substrings of the saved texts, selected because they mention the subject of a question line.\n')
    A('## Question lines (keys used in every file)\n')
    A('The user\'s lines, verbatim. Q5 and Q7 are split into sub-keys because they contain several separate claims.\n')
    A('| Key | Line |\n|---|---|')
    for k, v in QL.items():
        A(f'| {k} | {v} |')
    A('\nHeader lines "What is still unmeasured:" and "Would the gaps change the answer?" carry no claim of their own.\n')

    A('## Files\n')
    A('| Path | What | Question lines |\n|---|---|---|')
    A(f'| `sources.csv` | one row per fetched source ({len(src)} rows; {len(ok)} status ok) | column `question_lines` |')
    A(f'| `excerpts.jsonl` | {len(exc)} verbatim passages, one JSON object per line | field `question_line` |')
    A(f'| `searches.csv` | {len(srch)} search/lookup records (query, date, tool, top result URLs) | all |')
    A(f'| `texts/<slug>.txt.gz` | extracted text of each source ({len(texts)} files, incl. `<slug>.pdf.txt.gz` for arXiv PDFs) | per `sources.csv` |')
    A(f'| `raw/<slug>.<part>.<ext>.gz` | raw HTTP bodies, gzip of the unchanged bytes ({len(raws)} files) | per `sources.csv` |')
    A(f'| `defillama/*.json.gz` + `defillama/index.csv` | raw DefiLlama API responses ({len(dl)} files) | Q4-OTHERCHAINS, Q1-V4GAP, Q2-OLDV2, Q6-BSCORDER |')
    A('| `collect/` | collector scripts, source list, excerpt specs, logs, checkpoint (see Reproduce) | - |\n')

    A('## Sources and the lines they relate to\n')
    A('Counts are excerpts in `excerpts.jsonl` per source. Title/authors/date as stated by the source (arXiv: abs-page metadata).\n')
    A('| Slug | Kind | Title | Authors / org | Date stated | Lines | Excerpts |\n|---|---|---|---|---|---|---|')
    for s in src:
        date = s['publication_date_if_stated']
        if len(date) > 60:
            date = date[:60] + '...'
        title = s['title'].replace('|', '/')[:110]
        auth = s['authors_or_org'].replace('|', '/')[:70]
        A(f"| `{s['slug']}` | {s['kind']} | {title} | {auth} | {date} | {s['question_lines']} | {ex_by_slug.get(s['slug'], 0)} |")
    A('\nExcerpts per question-line key: ' + ', '.join(f'{k} {ex_by_q.get(k, 0)}' for k in QL) + '.\n')

    A('## Related material saved by other collectors (not duplicated here)\n')
    A('- `research-material/01-v4-pools/hook-docs/` - Clanker, Zora, Doppler, Flaunch, Bunni and Uniswap v4 docs/source files (deployments, IPoolManager.sol, Hooks.sol, hooklist) and the Zora hook registry. Q1-V4GAP, Q5-V4LAUNCH, Q8-V4MEASURE.')
    A('- `research-material/06-other-chains-onchain/bsc/docs/` - BNB Chain BEPs (BEP-322 builder API, BEP-619 block interval, ...), 48Club / BlockRazor / Blocksmith / bloXroute builder docs and BNB Chain MEV blog posts. Q6-BSCORDER.')
    A('- `research-material/06-other-chains-onchain/solana/docs/` and `.../solana/tip-floor.jsonl` - Jito docs and tip-floor snapshots. Q4-OTHERCHAINS.')
    A('- `research-material/00-prior-runs/papers-fetched-earlier/` - the paper texts read in the earlier session (no provenance metadata); fresh copies of the same papers are here.')
    A('- `research-material/04-shallow-pools/MANIFEST.md` - Uniswap V2 `allPairsLength` on Base (Q2-OLDV2 on-chain count).')
    A('- `research-material/05-base-onchain/rsr-episode/` and `00-prior-runs/competitor-ledgers/` - the RSR trade itself (Q5-CONTEST).\n')

    A('## Schemas\n')
    A('### sources.csv\n')
    A('| Column | Meaning |\n|---|---|')
    A('| slug | identifier; also the file stem in `texts/` and `raw/` |')
    A('| url | URL fetched (arXiv: abs URL of the version fetched) |')
    A('| title | title as stated (arXiv `citation_title`; HTML `og:title`/`<title>`; Discourse topic title; for text/markdown files the document\'s own heading, set in `collect/sources.json`) |')
    A('| authors_or_org | arXiv `citation_author` list; HTML meta author; otherwise the publishing organisation (set in `collect/sources.json`); for Discourse the opening-post author and the post that holds the cited text |')
    A('| publication_date_if_stated | arXiv: v1 date and full submission history; HTML: `article:published_time`/JSON-LD `datePublished` if present; Discourse: topic/post creation time; a date taken from the page body is marked "stated in page body"; empty otherwise |')
    A('| fetched_at_utc | time the fetch of that source finished (UTC) |')
    A('| access_notes | HTTP outcome, redirects, versions, pages; plus the collector\'s note on why the source was collected |')
    A('| question_lines | space-separated keys (table above) |')
    A('| kind | arxiv, html, discourse, pdf, text, json (json: body saved unchanged, used as its own text) |')
    A('| text_files | extracted text file(s) |')
    A('| raw_files | raw HTTP bodies (gzip) |')
    A('| status | `ok` or `failed: <reason>` |\n')
    A('### excerpts.jsonl\n')
    A('| Field | Meaning |\n|---|---|')
    A('| slug | source slug |')
    A('| question_line | key |')
    A('| quote | exact substring of `text_file` (original line breaks kept) |')
    A('| location | section / table / page as labelled in the source |')
    A('| text_file | the text file the quote was taken from |')
    A('| char_start, char_end | Python character offsets of the quote in the decompressed text file (`text[char_start:char_end] == quote`) |\n')
    A('Built by `collect/build_excerpts.py` from `collect/excerpt-specs.jsonl`; a spec gives the passage (or its first and last words, or `abstract: true`)')
    A('and the matcher locates it with whitespace and typographic-quote tolerance, then writes the exact original substring. `abstract: true` takes the')
    A('arXiv abstract as printed on the abs page (copied into the text header). Unlocated specs go to `collect/excerpt-failures.jsonl` (empty at generation time')
    A('unless listed under Coverage limits).\n')
    A('### texts/*.txt.gz\n')
    A('- arXiv `<slug>.txt.gz`: header (arXiv id and version, title, authors, submission history, comments, abstract from the abs page), then')
    A('  `=== full text (arxiv.org/html, LaTeXML) ===` with the HTML full text converted to text: MathML replaced by its LaTeX `alttext`, table rows as')
    A('  cells joined by ` | `, footnote marks appear inline (e.g. `1515` = footnote 15), figures are captions only. If arXiv has no HTML version, the text is the PDF text.')
    A('- arXiv `<slug>.pdf.txt.gz`: same header + PyMuPDF text of the PDF with `=== page N ===` markers (for page citations). Not proof-read.')
    A('- html: `Source URL`, `Final URL`, `Page title` header, then the text of `<main>`/`<article>` if present (else `<body>`), then')
    A('  `=== hyperlinks in the extracted part of the page ... ===` (anchor text TAB href; derived).')
    A('- discourse: topic header, then the Discourse `/raw/<topic>` markdown of all posts; each post is headed `username | time | #n`.')
    A('- text: the response body unchanged (markdown, SQL, llms.txt).\n')
    A('### raw/\n')
    A('`<slug>.<part>.<ext>.gz` = gzip of the HTTP response body. Parts: `abs` (arXiv abs page), `html-vN`, `pdf-vN`, `page`, `topic` (Discourse JSON),')
    A('`raw` (Discourse markdown), `body`, `doc`. sha256 of every response body is in `collect/fetch-log.jsonl`.\n')
    A('### defillama/\n')
    A('`overview-dexs-<chain>.json.gz` = gunzip gives the exact body of `https://api.llama.fi/overview/dexs/<chain>?excludeTotalDataChart=false&excludeTotalDataChartBreakdown=false`')
    A('(chains: base, arbitrum, optimism, unichain, ethereum, polygon, bsc, solana). `summary-dexs-<protocol>.json.gz` = body of')
    A('`https://api.llama.fi/summary/dexs/<protocol>` (uniswap-v4, uniswap-v2, uniswap-v3, and the parent `uniswap`). Top-level keys include')
    A('`totalDataChart` ([unix_day_utc, usd_volume]), `totalDataChartBreakdown` ([unix_day_utc, {protocol: usd_volume}]), `total24h`, `total7d`, `total30d`,')
    A('`protocols` (overview) or `chainBreakdown` (summary). Daily points end at unix 1790726400 = 2026-09-30T00:00Z. `index.csv`: file, url, http_status,')
    A('bytes, sha256 (of the uncompressed body), fetched_at_utc.\n')
    A('| File | HTTP | Bytes (uncompressed) | Fetched (UTC) |\n|---|---|---|---|')
    for r in dl:
        A(f"| `defillama/{r['file']}` | {r['http_status']} | {r['bytes']} | {r['fetched_at_utc']} |")
    A('')
    A('### searches.csv\n')
    A('query (search string, or a description of a direct lookup such as a sitemap or bibliography scan), date, tool (WebSearch, WebFetch, curl, arXiv HTML),')
    A('top_result_urls (space-separated, in the order returned). Web search rankings are not reproducible; the rows record what was returned on 2026-09-30.\n')

    A('## Time window\n')
    A(f'All HTTP requests: {tfirst} to {tlast} (UTC), 2026-09-30. Responses by HTTP status: ' + ', '.join(f'{k}: {v}' for k, v in sorted(status_codes.items())) + '.')
    A('Documents are as served at fetch time; arXiv versions are pinned in `sources.csv`/`texts` headers.\n')

    A('## Reproduce\n')
    A('```bash')
    A('cd research-material/08-sources/collect')
    A('export REQUESTS_CA_BUNDLE=/root/.ccr/ca-bundle.crt SSL_CERT_FILE=/root/.ccr/ca-bundle.crt   # only behind the proxy')
    A('python3 fetch_sources.py            # fetch every entry of sources.json not yet fetched (checkpoint: fetch-state.json); --force refetches all, --only SLUG...')
    A('python3 fetch_defillama.py          # raw DefiLlama JSON into ../defillama/ (resumable; --force)')
    A('python3 build_excerpts.py           # ../excerpts.jsonl from excerpt-specs.jsonl (fails are listed, never silently dropped)')
    A('python3 make_searches_csv.py        # ../searches.csv from searches.jsonl')
    A('python3 make_manifest.py            # this file')
    A('```')
    A('Requirements: python3 with requests, beautifulsoup4, PyMuPDF (`fitz`). Requests are sequential per host with >= 1.5-3 s spacing;')
    A('HTTP 429/5xx are retried with backoff honouring Retry-After. Logs: `collect/fetch_sources*.log`, `collect/fetch_defillama.log`, `collect/fetch-log.jsonl`.\n')

    A('## Coverage limits and gaps\n')
    for g in GAPS:
        A('- ' + g)
    if bad:
        A('- Sources whose fetch failed: ' + '; '.join(f"`{s['slug']}` ({s['status']})" for s in bad))
    fails = [json.loads(l) for l in open(os.path.join(HERE, 'excerpt-failures.jsonl')) if l.strip()]
    if fails:
        A('- Excerpt specs that could not be located: ' + '; '.join(f"`{f['slug']}` ({f['error']})" for f in fails))
    A('')
    with open(os.path.join(OUT, 'MANIFEST.md'), 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('MANIFEST.md written;', len(src), 'sources,', len(exc), 'excerpts')


GAPS = [
    'Entropy Advisors: no standalone report was found. The figures quoted in docs/ANALYSIS.md 4.1 (share of atomic-arbitrage revenue retained: '
    'Arbitrum 1.74 %, Ethereum 28.83 % via MEV-Boost, Base 7.34 % via priority fees) appear in a forum post by the account "Entropy" (Entropy Advisors), '
    'post #7 (2026-06-16) in the Arbitrum forum thread on replacing Timeboost with PGA, which describes them as "research on revenue capture specifically '
    '(conducted in March 2026)". The underlying dataset/report behind that post was not located (queries in searches.csv; the Entropy monthly updates for '
    'Feb-Jun 2026 and the dashboards catalog were checked by text search). The dashboards catalog post is saved; the Dune dashboards themselves were not '
    'fetched (client-side rendered, need an API key).',
    'docs.base.org: the Base docs do not publish an "atomic-arbitrage revenue share"; the saved Base pages are the ordering / Flashblocks / fee / Denim / '
    'Jovian pages. Old URLs /base-chain/network-information/transaction-ordering, /block-building and /base-chain/flashblocks/faq redirect to the saved '
    'pages (recorded in collect/fetch-log.jsonl). https://docs.base.org/get-started/launch-token now redirects to an unrelated B20 asset-token page and '
    'was dropped. The Base tweet on the minimum-base-fee increase cited by arXiv 2606.00720 [7] (x.com) was not fetched: x.com needs a login.',
    'arXiv 2509.22143 (Messias & Torres): both v2 (current, 2026-07-21) and v1 (2025-09-26) are saved. The text states totals (Table 3), per-arbitrage '
    'means and the MEV-data period (2025-04-17 to 2025-07-31); neither version states a per-day arbitrage profit figure (text search of the HTML and PDF '
    'texts for "per day", "a day", "/day", "4.7K", "4,7": the only hits are other numbers such as 14,796,548; "daily" occurs only for transaction counts). The per-day figure in the '
    'question line therefore has no verbatim excerpt; the totals, period and per-arbitrage means are excerpted.',
    'Scope of the Q7 figures as stated in the sources: arXiv 2607.24172 (Pahari, Messias, Torres) states the 82 % -> 28 % profitable-bot figure for Base '
    'over 2023-09-01 to 2025-07-31, for speculative, non-speculative and hybrid arbitrage and liquidation bots (Table 6); arXiv 2606.00720 (Wu & Oz) states '
    '21,374,434 arbitrages by 4,365 bot addresses for 2025-06-01 to 2026-02-28. Each paper\'s data period and detection method are excerpted '
    '(Q7-CHAINWIDE-METHOD, Q7-PROFIT-28, Q7-BASE-21M).',
    'Detection coverage of the studies: arXiv 2606.00720 extends the method of arXiv 2506.14768, which reads swaps from Dune `dex.trades` and pool '
    'interactions from `dex.raw_pools`. The Dune Spellbook model files listing which DEX projects feed `dex.trades` on Base, Arbitrum, Optimism and BNB '
    'are saved as of fetch time (main branch; the commit hash could not be read: api.github.com answered HTTP 403 unauthenticated). The Spellbook '
    'history (which projects were included during each study window) was not collected.',
    'Text extraction: HTML and PDF are converted to text by collect/fetch_sources.py; formulas, tables and footnotes are flattened, figures are not '
    'captured (only captions). PDF text (texts/*.pdf.txt.gz) was not proof-read. The raw HTML/PDF bytes are kept in raw/ for re-extraction.',
    'developers.uniswap.org answered HTTP 429 (Retry-After 507 s, then 3600 s). The PoolManager and Hooks pages were fetched after waiting; the '
    'collector was then stopped and the Dynamic Fees and v2 Deployments pages were taken from the site\'s source files on GitHub '
    '(raw.githubusercontent.com/Uniswap/docs/main/content/protocols/..., kind text). The collector now caps Retry-After at 900 s.',
    'Discourse threads (Arbitrum forum, Flashbots collective) are saved as the /raw markdown of all posts; images embedded in posts are not saved.',
    'Sources fetched but dropped after reading because they did not relate to any question line: arXiv 2609.18975 (pump.fun pipeline coverage), '
    'arXiv 2512.00377 (memecoin fragility index), arXiv 2603.13830 (BSC rug-pull warning, 7 tokens), docs.base.org configuration reference, '
    'docs.base.org launch-token (redirect). They were removed from sources.json and from texts/ and raw/.',
    'Not collected: X/Twitter posts; Dune dashboards; paywalled or login-only reports; news articles and SEO blogs returned by searches (listed in '
    'searches.csv only); Telegram/Discord statements; the 0x report\'s underlying data (only the published post). No peer-reviewed or arXiv study '
    'specific to Clanker/Zora/Virtuals launch sniping on Base was found by the searches in searches.csv (launch-related sources saved are the platform '
    'docs, Wu & Oz Section 5.3, and Solana/cross-chain memecoin studies).',
    'Solana, BSC and other-L2 coverage in this folder is limited to published sources; on-chain data for those chains is in research-material/06-*.',
    'Date fields: several web pages state no publication date in their metadata (publication_date_if_stated left empty). Dates visible only in the '
    'page body were copied only for the 0x post and the Uniswap Foundation post (marked "stated in page body"); for other pages they remain in the text files.',
    'arXiv HTML artefact: in the LaTeXML HTML of arXiv 2509.22143v1, digit-group separators render as the word "true" (e.g. "11true613true936" for '
    '11,613,936). Excerpts from v1 are therefore taken from the PDF text (texts/arxiv-2509.22143v1-...pdf.txt.gz); the HTML-derived v1 text is kept unchanged.',
]

if __name__ == '__main__':
    main()
